apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 1.4.0
    prometheus: k8s
    role: alert-rules
  name: node-exporter-rules-longevity
  namespace: openshift-monitoring
spec:
  groups:
  - name: longevity
    rules:
    - alert: NodeMemoryAlert_Longevity
      annotations:
        description: Memory utilization on Node {{ $labels.instance }} is currently
          at {{ printf "%.2f" $value }}%.
        summary: You are using a lot of memory
      expr: |
        (
          (instance:node_memory_utilisation:ratio{job="node-exporter"} * 100) > 60
        )
      for: 1m
      labels:
        severity: critical

    - alert: HighCPU_Longevity
      annotations:
        description: CPU utilization on Node {{ $labels.instance }} is currently
          at {{ printf "%.2f" $value }}%.
        summary: CPU utilization is high for more than 5 min
      expr: |
        (
          100 - (100 * avg(irate(node_cpu_seconds_total{mode="idle"}[1m])) by (instance)) > 50
        )
      for: 5m
      labels:
        severity: critical

    - alert: FSFullPredict_Longevity
      annotations:
        description: FS mountpoint {{ $labels.mountpoint }} on {{ $labels.instance }} will be full in 3 days.
        summary: FS will be full in 3 days.
      expr: |
        (
          predict_linear(node_filesystem_free_bytes[1h], 72 * 3600) < 0
        )
      for: 5m
      labels:
        severity: critical

    - alert: ContainerRestarts_Longevity
      annotations:
        description: Container {{ $labels.container }} in pod {{ $labels.pod }} was restarted {{ printf "%.2f" $value }}%.
        summary: Container restarted more than once in last 10 min.
      expr: |
        (
          increase(kube_pod_container_status_restarts_total[10m]) > 1
        )
      labels:
        severity: critical

    - alert: RootFS_Longevity
      annotations:
        description: Root FS on Node {{ $labels.instance }} is
          at {{ printf "%.2f" $value }}%.
        summary: Root FS is more than 50%
      expr: |
        (
          100 - ((node_filesystem_avail_bytes{mountpoint="/"}/node_filesystem_size_bytes{mountpoint="/"}) * 100 ) > 50
        )
      for: 5m
      labels:
        severity: critical

    - alert: DroppedRequestsForKubeApi_Longevity
      annotations:
        description: There are dropped requests for kube-apiserver. Please check the system status.
        summary: There are dropped requests for the kube-apiserver.
      expr: |
        (
          sum(rate(apiserver_dropped_requests_total{apiserver="kube-apiserver"}[5m])) by (request_kind) > 0
        )
      for: 1m
      labels:
        severity: critical

    - alert: FailedPods_Longevity
      annotations:
        description: There are failed pods in the system.
        summary: There are failed pods in the system.
      expr: |
        (
          sum(kube_pod_status_phase{phase="Failed"}) > 0
        )
      for: 1m
      labels:
        severity: critical

    - alert: APIResponseTime_Longevity
      annotations:
        description: API Response Time for request type {{ $labels.verb }} is  {{ printf "%.2f" $value }}% seconds.
        summary: API Response Time is more than 1 sec.
      expr: |
        (
          histogram_quantile(0.99,sum(rate(apiserver_request_duration_seconds_bucket{apiserver="kube-apiserver",subresource!="log",verb!~"WATCH|WATCHLIST|PROXY"}[5m])) by (verb,le)) > 1
        )
      for: 5m
      labels:
        severity: critical

    - alert: PodPossibleMemoryLeak_Longevity
      annotations:
        description: Min memory usage of pod {{ $labels.pod }} increased
          by {{ printf "%.2f" $value }}% over 1 week.
        summary: Please check for the memory leak.
      expr: |
        (
          (sum(min_over_time(container_memory_working_set_bytes{namespace=~"multicluster-engine|openshift-machine-api",pod=~".*assisted.*|.*metal.*",container!="POD"}[12h] ) )by(pod) /  sum(min_over_time(container_memory_working_set_bytes{namespace=~"multicluster-engine|openshift-machine-api",pod=~".*assisted.*|.*metal.*",container!="POD"}[12h] offset 1w ) )by(pod) - 1) * 100
        ) > 10
      for: 1m
      labels:
        severity: critical