apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 1.4.0
    prometheus: k8s
    role: alert-rules
  name: node-exporter-rules-vlad
  namespace: openshift-monitoring
spec:
  groups:
  - name: longevity
    rules:
    - alert: NodeMemoryAlert_Longevity
      annotations:
        description: Memory utilization on Node {{ $labels.instance }} is currently
          at {{ printf "%.2f" $value }}%.
        summary: You are using a lot of memory
      expr: |
        (
          (instance:node_memory_utilisation:ratio{job="node-exporter"} * 100) > 10
        )
      for: 1m
      labels:
        severity: critical

    - alert: DroppedRequestsForKubeApi_Longevity
      annotations:
        description: There are dropped requests for kube-apiserver. Please check the system status.
        summary: There are dropped requests for the kube-apiserver.
      expr: |
        (
          sum(rate(apiserver_dropped_requests_total{apiserver="kube-apiserver"}[5m])) by (request_kind) > 0
        )
      for: 1m
      labels:
        severity: critical

    - alert: FailedPods_Longevity
      annotations:
        description: There are failed pods in the system.
        summary: There are failed pods in the system.
      expr: |
        (
          sum(kube_pod_status_phase{phase="Failed"}) > 0
        )
      for: 1m
      labels:
        severity: critical

    - alert: PodPossibleMemoryLeak_Longevity
      annotations:
        description: Min memory usage of pod {{ $labels.pod }} increased
          by {{ printf "%.2f" $value }}%.
        summary: Please check for memory leak.
      expr: |
        (
          (sum(min_over_time(container_memory_working_set_bytes{namespace="multicluster-engine",pod=~".*assisted.*",container!="POD"}[12h] ) )by(pod) /  sum(min_over_time(container_memory_working_set_bytes{namespace="multicluster-engine",pod=~".*assisted.*",container!="POD"}[12h] offset 1w ) )by(pod) - 1) * 100
        )
      for: 1m
      labels:
        severity: critical